### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by AlexanderDKazakov** [RamanathanVaradharajan/Namics#22]
Output.cpp offer 2 way of saving outputs. Recently I figured out that if I have not "output" folder so I get a segfault (next iterations leads to a segfault too (although output exists) ). I am planning to write checking procedure of such folders. But at the same time, do we need 2 way of saving data?

#Updated
Only one way. Now I got it.

**Comment by Dmry** [comment]
My implementation was indeed a little crude, my apologies.  My idea was to keep your input folder clean and accessible, whilst maintaining the possibility to run input files from somewhere other than inputs.

I've updated my branch with an empty output folder to take care of this issue. It also includes a .gitignore to make sure our repo doesn't get bloated with output files. It should find its way to the master branch soon. You can always disable the output folder using the [output : brand : use_output_folder : false] trigger in your input file.

If you run into issues again, let me know and I'll take my responsibility to fix them.
