### ISSUE TITLE
CUDA for cleng not working

### ISSUE THREAD

**Issue by Dmry** [RamanathanVaradharajan/Namics#54]
After merging master into mesodyn, I ran into a ton of new errors. Working on debugging this now.

**Comment by Dmry** [comment]
Cleng should now also work after merging with the master branch. Still no (correct) convergence though.

**Comment by AlexanderDKazakov** [comment]
Now I again can work on Namics :) I will check it. Thanks)

**Comment by RamanathanVaradharajan** [comment]
Currently Frans and Myself are working on some SCF features of Namics (mostly to solve membrane problems). @Dmry  @AlexanderDKazakov  Keep us updated about cuda progress, hopefully we might find some time in future to work on it as well.

**Comment by Dmry** [comment]
So current status is:

- Compiles
- Runs
- No convergence

Suspect for me is some incorrect or missing data transfer between cleng and namics, possibly due to the pre-processor directive `#ifdef CUDA`
