### ISSUE TITLE
Many output functions / pushes are incompatible with CUDA.

### ISSUE THREAD

**Issue by Dmry** [RamanathanVaradharajan/Namics#56]
Need to debug this per class, probably.

**Comment by AlexanderDKazakov** [comment]
How about **new** separate class? We can create some "Pusher" class for pushing or writing output. What do you think? 

Could you, please, give an example of incompatibility?

**Comment by AlexanderDKazakov** [comment]
Why do you close it? Is it resolved?

**Comment by Dmry** [comment]
One example of incompatibility are in writing profiles (e.g. phi). The variables are all stored as device variables and there's not check to transfer them to host before writing.

The mesodyn folder contains an extensible & object oriented file writer that works with CUDA and can write kal, csv, pro and 2 types of vtk. We will probably be able to re-purpose that for the modules that would like to write CUDA data.

**Comment by Dmry** [comment]
For reference, the way it works is, after including the header:

```
Writable_file out_file(filename.str(), output_profile_filetype ); // see header for class Writable_filetype
profile_writers.push_back(Profile_writer::Factory::Create(output_profile_filetype, Lat[0], out_file)); profile_writers[0]->bind_data(output_profiles);
```

output_profiles is a map that associated the string name to a class that converts any data pointer to string:

```
map<std::string, shared_ptr<IOutput_ptr> > output_profiles;
```

I also have a helper function to help you populate the map more easily (found in mesodyn.h):
assuming phi is a pointer to the first element of your system-volume-inc-boundaries (M) sized array
```
    for (size_t i = 0 ; i < components.size() ; ++i)
    {
      string description = "component:" + to_string(i);
      register_output_profile(description + ":density", phi);
    }
```

Writing data is then as easy as:
```
    for (auto& profile_writer : profile_writers)
    {
      profile_writer->prepare_for_data();
      profile_writer->write();
    }
```

**Comment by Dmry** [comment]
@RamanathanVaradharajan 

Another (less intrusive) method would be to change to unified memory. We only have to replace cudaMalloc with cudaMallocManaged and then prefetch with cudaMemPrefetchAsync instead of TransferDataToX. 

I think that way we can hit two birds with one stone:

- No issues when writing to file
- No more need to transfer between device and host explicitly, will greatly reduce the development and debugging time needed to keep CUDA up and running.
