### ISSUE TITLE
Need to set up and document unit testing

### ISSUE THREAD

**Issue by Dmry** [RamanathanVaradharajan/Namics#57]

**Comment by RamanathanVaradharajan** [comment]
@AlexanderDKazakov 
Unit testing is complicated and needs dedicated software development (means more time investment). However we can do test it based on performance of program. Easiest way to implement such a feature would be to develop test files of basic models for problems you would like to solve. Software people have a name for such procedure as well **Black Box Testing**

For ex. I can say how I am planning to do it. 
I develop Teng (monte carlo to move tagged and pinned points). I can make these small model inputs,
1. 1D problem of interface (two liquids) 
2. 1D problem of interface (two liquids) with a diblock copolymer (Lets call this emulsion) **Just to make sure that any new feature hasn't spoiled existing framework**
3. 1D problem of emulsion with all diblock polymers having a tagged segment **Now I know if freedom tag works**
4. 1D problem with tagging (cylindrical and spherical geometry) **Not necessary, I do it anyway to make sure that geometry works**
5. 3D problem without tagging just two liquids.
6. 3D problem of emulsion
7. 3D problem of emulsion with one polymer tagged/pinned.
8. Same with several polymer pinned.
** If everything until here works, it means  basic SCF part works**
8. Small 3D problem with MonteCarlo but pin only one polymer. (Not more than 10 steps, 50 layers)
9. Small 3D problem with MonteCarlo pin multiple points. 

Once this is done. I will upload a directory to git named `black_box_testing/teng/*.in`
You can do the same. 

This means. 
Add feature.
compile.
git commit. git pull master. git merge.(fix conflicts)
build application (namics). 
Use it to run all the inputs in black_box_testing/teng/*.in
git push (only if every file creates perfect output. This part of result checking is manual, unfortunately).
create pull request.

**Comment by AlexanderDKazakov** [comment]
Hi! 

I already have implemented this in my branch. It was cost only one additional header and one class for namics_config.
